### ISSUE TITLE
Map View not working

### ISSUE THREAD

**Issue by vostronix** [derjasper/TankenApp#15]
The map service will no longer be made available

**Comment by derjasper** [comment]
Thank you for reporting. I will investigate this when I finished my exams ;)

**Comment by derjasper** [comment]
I welcome any contribution adding a working map to TankenApp so the new version can be released. The only requirement is that is uses OpenStreetMap to support open data.
The QML Map type is broken (at least in Ubuntu). I did not receive any answer for my bug report yet and am tired of looking for alternatives, so I'll wait until there is a simple replacement available.
