### ISSUE TITLE
Spritpreisrechner.at (Austria) broken

### ISSUE THREAD

**Issue by wrogner** [derjasper/TankenApp#20]
After choosing spritpreisrechner.at as source, a message appears falsely claiming missing internet connect.

It seems that the database has been relocated.

**Comment by derjasper** [comment]
Cannot reproduce. In the app, I get the same stations as here: http://www.spritpreisrechner.at/ts/map_gas.jsp (at least for Vienna)

Can you give me more details? Which location is affected and what are your filter settings?

**Comment by wrogner** [comment]
I use OTA-13 form 20.9.2016

Selected Diesel and Super 95 (Fuel95)
Selected different radiuses
Only By Price shown (in other sources By Distance added)

Using Geolocation, list stays empty
selecting a location manually brings an empty list for Wiener Neudorf / Wr. Neudorf

**Comment by derjasper** [comment]
Sorry, cannot reproduce :/ I get some results for the given location, although I'm not sure if the radius setting is working properly.

>  Only By Price shown (in other sources By Distance added)

This is intentional, the API endpoint does not support sorting by distance

**Comment by wrogner** [comment]
Sounds very unfortunate.
I consider reverting back to an Android telephone.
Thanks and good luck
