### ISSUE TITLE
No price from TankerKönig

### ISSUE THREAD

**Issue by dayrover** [derjasper/TankenApp#21]
Currently the app is not able to show any prices on my phone running Ubports R3.
Not sure if the is an API problem or an App problem.
Queries never return a result and the follow error log is recorded:
tankerkoenig.js:31: TypeError: Cannot call method 'toFixed' of null

Not sure if this is  symptom or the cause.

**Comment by dayrover** [comment]
The problem is that in my locality TankerKönig is return a Station with 'null' price.

I've fixed this and also added exception handling so an error is return in the UI in such cases

**Comment by derjasper** [comment]
Thank you for reporting and fixing it!
I will release this version soon ;)

**Comment by derjasper** [comment]
Ok it seems that I am too stupid to get my own app to build, the last time was some time ago, and the way it used to work seems to be broken with the current Ubuntu SDK. Did you manage to build the app on your machine? If yes, how did you configure the SDK? Thanks ;)

**Comment by dayrover** [comment]
I found the Ubuntu SDK totally flacky even when it was still supported. Every few weeks it would break. I guess if you have 16.04 it may still be possible to install. I use 'clickable' to do the build now. I installed direct from GitHub (https://github.com/bhdouglass/clickable.git) and then setup it up to use a Docker container to build. Since I already had Docker installed I had to comment out the following line in the 'clickable' Python script as I already have a 'docker' user:

`subprocess.check_call(shlex.split('sudo groupadd docker'))
subprocess.check_call(shlex.split('sudo usermod -aG docker $USER'))
`
After that I just run 'clickable' in the TankenApp directory and it built and uploaded the new version to my phone!

**Comment by derjasper** [comment]
Ok thanks for the hint! At least it builds the app without errors and puts together sth that is actually executable!
Unfortunately, I cannot manage to build a package using the "all" architecture, which seems to be necessary to be accepted in the store. Even editing the manifest files and putting the parts of the click archive together manually does not work... If you got an idea let me know :S

**Comment by dayrover** [comment]
I've tried to see what is going on by submiting click packages to the OpenStore myself. I also got 'This app needs to be reviewed manually, please check you app using the click-review command'.
Comparing the file layout of the 'clickable' package with 0.4.9 I found no differences. I tried building an uploading with various manifests without luck. I guess we need to ask the OpenStore team what the click package ist not accepted.

**Comment by derjasper** [comment]
I filed a bug at https://github.com/UbuntuOpenStore/openstore-meta/issues/177

**Comment by derjasper** [comment]
Ok, the new release is in the store. Can you confirm that everything works as expected?

**Comment by dayrover** [comment]
Works fine. Thanks for your work.

**Comment by derjasper** [comment]
Thanks for your help and patience ;)
