### ISSUE TITLE
Showing wrong map/location

### ISSUE THREAD

**Issue by toehold** [derjasper/TankenApp#23]
I use the https://carburanti.mise.gov.it/OssPrezziSearch/ source, select a place, select the first result, click on it and it is showing my the wrong map/location. Using the website it shows the correct location!

thanks

**Comment by derjasper** [comment]
I cannot reproduce this issue. Please give me a concrete reproducible example. Please check also the "Navigate" buttons shown in the detail view as well as the overview map.
