### ISSUE TITLE
No Place selection

### ISSUE THREAD

**Issue by Linouli** [derjasper/TankenApp#24]
I like to use the TankenApp on my BQ E5 with Ubuntu Touch, but it doesn't work anymore. A new installation did not bring any success. The German data source is set. However, if a location is entered, it is not selectable. Is there a solution to this? Thank you.

**Comment by derjasper** [comment]
It seems to be a problem with the platform, maybe the server has been shut down or sth. I will try to find that out...

**Comment by derjasper** [comment]
The bug should be fixed now! Thanks for reporting ;)

**Comment by Linouli** [comment]
Thanks for the quick fix, the helpful app and your time. Now everything works perfectly
