### ISSUE TITLE
Please add also also alternative fuel like cng or lpg in Europe

### ISSUE THREAD

**Issue by toraschi** [derjasper/TankenApp#27]
Please add also also alternative fuel like cng or lpg in Europe
this could be a source
https://cngapp.gibgas.de

**Comment by derjasper** [comment]
This source is not open, so I cannot add this source. However I am open to add support for CNG and LPG, if there is a good and open source ;)
If you know any, let me know

**Comment by toraschi** [comment]
hallo,
hm, I'm sorry . try to find another source hope to find one

**Comment by toraschi** [comment]
Hello derjasper,
perhaps this source is better:
httpw://gas.tankstellen.de
