### ISSUE TITLE
Extend to France

### ISSUE THREAD

**Issue by derjasper** [derjasper/TankenApp#6]
France has offical price data at http://www.prix-carburants.gouv.fr/. This may be a legal issue (http://www.prix-carburants.gouv.fr/rubrique/cgu/), perhaps ask for permission.

**Comment by xXSparkeyy** [comment]
Hi, they recently changed the license to open data, u can use the data for free now, if u name them as source.

**Comment by derjasper** [comment]
Thanks for the hint!

I will add it as soon as I have time ;)
