### ISSUE TITLE
uNav and OSMScout support

### ISSUE THREAD

**Issue by XxPhenixX** [derjasper/TankenApp#7]
Hello,
first thanks for this great app!
Can you add an uNav and OSMScout support for the navigation instead (in addition) of the HEREmaps app?
Greetings

**Comment by derjasper** [comment]
Yes, that would be a nice feature. When releasing the first implementation, no apps having URL dispatchers have been available.
I'll add the https://en.wikipedia.org/wiki/Geo_URI_scheme as second option.
It seems that uNav already has this implemented, while OSMScout has not (I filed a bug). Moreover, someone filed a bug for OSMTouch.

**Comment by derjasper** [comment]
New version is in the store, should work with uNav.

**Comment by XxPhenixX** [comment]
Thanks for the fast answer.
But unfortunately does the new "Navigieren" button nothing.

**Comment by derjasper** [comment]
published a new version, please tell me if it works. the emulator is currently broken and I do not own an ubuntu phone, so I do not have the possibility to test this feature.

**Comment by XxPhenixX** [comment]
Yeah.
It's working!
Maybe you call it "Navigieren mit Unav" or have a subtitle under the address: "Navigieren mit:" and then the two buttons "uNav" and "HEREMaps"

**Comment by derjasper** [comment]
Thanks for your feedback!
If more apps implement the URL dispatcher, Ubuntu will give you a list of apps when clicking the first button. The second button is only for HERE as it does use another url dispatcher, however HERE is preinstalled on many devices and should be integrated with the app. 
I will think about another design, i.e. unifying the buttons.

**Comment by derjasper** [comment]
Currently, the UITK does not have any nice possibility to unify the two buttons. Perhaps the design will be changed in future. Since the original bug is fixed I close this issue.
